# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Anatole"
license = "MIT"
licenselink = "https://github.com/lxndrblz/anatole/blob/master/LICENSE"
description = "Anatole is a beautiful minimalist two-column hugo theme based on farbox-theme-Anatole."
homepage = "https://github.com/lxndrblz/anatole/"
tags = ["blog", "responsive", "clean", "minimalist", "minimal", "personal", "dark"]
features = ["blog", "seo", "responsive", "mobile", "disqus", "fontawesome", "analytics", "math"]
min_version = "0.53.0"

[author]
  name = "Alexander Bilz"
  homepage = "https://alexbilz.com"

# If porting an existing theme
[original]
  author = "Cai Cai"
  homepage = "https://www.caicai.me/"
  repo = "https://github.com/hi-caicai/farbox-theme-Anatole"
  
  [build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.82.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


